name: build-and-deploy
on:
  push:
    branches: ["main"]
    paths:
      - "web-revised/**"
      - "was/**"
      - "apps/web-frontend/**"
      - "apps/was-api/**"

permissions:
  contents: write

concurrency:
  group: build-deploy
  cancel-in-progress: true

jobs:
  web-frontend:
    if: github.actor != 'github-actions[bot]'   # 봇 커밋 재트리거 방지
    runs-on: ubuntu-latest
    env:
      CONTEXT_DIR: web-revised
      MANIFEST_DIR: apps/web-frontend
      IMAGE: ghcr.io/<<너의 GHCR 아이디>>/<<web-리포>>
      TAG: v${{ github.run_number }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_USERNAME: admin
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Check changes (web)
        id: web_changed
        run: |
          if git diff --quiet HEAD^ HEAD -- "$CONTEXT_DIR" "$MANIFEST_DIR"; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        if: steps.web_changed.outputs.changed == 'true'
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u <<너의 GHCR 아이디>> --password-stdin

      - name: Build & Push (web)
        if: steps.web_changed.outputs.changed == 'true'
        run: |
          docker build -t $IMAGE:$TAG "$CONTEXT_DIR"
          docker push $IMAGE:$TAG

      - name: Install yq
        if: steps.web_changed.outputs.changed == 'true'
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update manifests image (web-frontend)
        if: steps.web_changed.outputs.changed == 'true'
        run: |
          set -e
          find "$MANIFEST_DIR" -type f \( -iname "*deploy*.y*ml" -o -iname "*deployment*.y*ml" \) -print0 \
          | xargs -0 -I{} sh -c 'yq -i '"'"'(.spec.template.spec.containers[].image) = env(IMAGE) + ":" + env(TAG)'"'"' "{}"'
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "web-frontend: set image to $IMAGE:$TAG [skip ci]"
            git push
          else
            echo "No manifest changes to commit."
          fi

      - name: ArgoCD Login & Sync (web-frontend)
        if: steps.web_changed.outputs.changed == 'true' && env.ARGOCD_SERVER != ''
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure --grpc-web
          argocd app sync web-frontend --prune --grpc-web
          argocd app wait web-frontend --health --sync

      - name: Notify Slack (success)
        if: steps.web_changed.outputs.changed == 'true' && success()
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            ✅ *배포 성공 (web-frontend)*
            • Image: `${{ env.IMAGE }}:${{ env.TAG }}`
            • Ref: `${{ github.ref_name }}`
            • Actor: `${{ github.actor }}`
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack (failed)
        if: steps.web_changed.outputs.changed == 'true' && failure()
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            ❌ *배포 실패 (web-frontend)*
            • 로그: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  was-api:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    env:
      CONTEXT_DIR: was                 # 트리거와 일치
      MANIFEST_DIR: apps/was-api
      IMAGE: ghcr.io/<<너의 GHCR 아이디>>/<<was-리포>>
      TAG: v${{ github.run_number }}
      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
      ARGOCD_USERNAME: admin
      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Check changes (was)
        id: was_changed
        run: |
          if git diff --quiet HEAD^ HEAD -- "$CONTEXT_DIR" "$MANIFEST_DIR"; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Login to GHCR
        if: steps.was_changed.outputs.changed == 'true'
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u <<너의 GHCR 아이디>> --password-stdin

      - name: Build & Push (was)
        if: steps.was_changed.outputs.changed == 'true'
        run: |
          docker build -t $IMAGE:$TAG "$CONTEXT_DIR"
          docker push $IMAGE:$TAG

      - name: Install yq
        if: steps.was_changed.outputs.changed == 'true'
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Update manifests image (was-api)
        if: steps.was_changed.outputs.changed == 'true'
        run: |
          set -e
          find "$MANIFEST_DIR" -type f \( -iname "*deploy*.y*ml" -o -iname "*deployment*.y*ml" \) -print0 \
          | xargs -0 -I{} sh -c 'yq -i '"'"'(.spec.template.spec.containers[].image) = env(IMAGE) + ":" + env(TAG)'"'"' "{}"'
          if ! git diff --quiet; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -am "was-api: set image to $IMAGE:$TAG [skip ci]"
            git push
          else
            echo "No manifest changes to commit."
          fi

      - name: ArgoCD Login & Sync (was-api)
        if: steps.was_changed.outputs.changed == 'true' && env.ARGOCD_SERVER != ''
        run: |
          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
          argocd login "$ARGOCD_SERVER" --username "$ARGOCD_USERNAME" --password "$ARGOCD_PASSWORD" --insecure --grpc-web
          argocd app sync was-api --prune --grpc-web
          argocd app wait was-api --health --sync

      - name: Notify Slack (success)
        if: steps.was_changed.outputs.changed == 'true' && success()
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            ✅ *배포 성공 (was-api)*
            • Image: `${{ env.IMAGE }}:${{ env.TAG }}`
            • Ref: `${{ github.ref_name }}`
            • Actor: `${{ github.actor }}`
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Notify Slack (failed)
        if: steps.was_changed.outputs.changed == 'true' && failure()
        uses: slackapi/slack-github-action@v1
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            ❌ *배포 실패 (was-api)*
            • 로그: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
