name: was-build
on:
  push:
    branches: [ "main" ]
    paths:
      - "was/**"
      - "apps/was-api/wasapp.yaml"

permissions:
  contents: write
  packages: write

concurrency:
  group: was-build
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/unklo1200/was-updated
      TAG: v${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR (unklo1200 namespace)
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u unklo1200 --password-stdin

      - name: Build & Push image
        run: |
          docker build -t $IMAGE:$TAG -f was/Dockerfile was
          docker push $IMAGE:$TAG
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE:$TAG)
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: Update kubernetes manifest with new image
        run: |
          sed -i "s#image: .*was-updated.*#image: ${DIGEST}#g" apps/was-api/wasapp.yaml
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git commit -am "chore(was): deploy ${TAG} (${DIGEST})" || echo "no manifest change"
          git push

      # (선택) 바로 Argo CD 동기화
      - name: Argo CD sync (optional)
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        run: |
          set -euo pipefail
          if [ -z "${ARGOCD_SERVER:-}" ] || [ -z "${ARGOCD_AUTH_TOKEN:-}" ]; then
            echo "Skipping Argo CD sync: missing secrets"; exit 0
          fi

          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

          timeout 3 bash -c "cat < /dev/null > /dev/tcp/${ARGOCD_SERVER}/443" \
            && echo "443 reachable" || (echo "443 not reachable to $ARGOCD_SERVER"; exit 1)

          argocd login "$ARGOCD_SERVER" --auth-token "$ARGOCD_AUTH_TOKEN" --grpc-web --insecure
          argocd account get-user-info
          argocd app sync was-api --grpc-web
