name: was-build
on:
  push:
    branches: [ "main" ]
    paths:
      - "was/**"
      - "apps/was-api/wasapp.yaml"

permissions:
  contents: write
  packages: write

concurrency:
  group: was-build
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE: ghcr.io/unklo1200/was-updated
      TAG: v${{ github.run_number }}

    steps:
      - uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u unklo1200 --password-stdin

      - name: Build & Push image
        run: |
          set -euo pipefail
          docker build -t $IMAGE:$TAG -f was/Dockerfile was
          docker push $IMAGE:$TAG
          DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE:$TAG)
          echo "DIGEST=$DIGEST" >> $GITHUB_ENV

      - name: Update manifest image
        run: |
          sed -i "s#image: .*was-updated.*#image: ${DIGEST}#g" apps/was-api/wasapp.yaml
          git config user.name "ci-bot"
          git config user.email "ci-bot@users.noreply.github.com"
          git commit -am "chore(was): deploy ${TAG} (${DIGEST})" || echo "no manifest change"
          git push

      - name: Argo CD sync (port-forward)
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
          APP_NAME: was-api
        run: |
          set -euo pipefail
          echo "::add-mask::${ARGOCD_AUTH_TOKEN}"
          echo "$KUBE_CONFIG_DATA" | base64 -d > "$HOME/.kube/config"
          chmod 600 "$HOME/.kube/config"

          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd

          kubectl -n argocd port-forward svc/argocd-server 8443:443 >/tmp/pf.log 2>&1 &
          PF_PID=$!
          for i in {1..20}; do curl -sk https://localhost:8443 && break || sleep 1; done

          argocd login localhost:8443 --auth-token "$ARGOCD_AUTH_TOKEN" --insecure
          argocd app sync "$APP_NAME" --grpc-web --prune
          argocd app wait "$APP_NAME" --health --timeout 300
          kill $PF_PID || true
